# 1. You are given two arrays:
# - `expected`: An array of expected output values.
# - `actual`: An array of actual output values generated by a program.
# Your task is to *compare* these two arrays element by element and:
# - Count how many *test cases passed* (i.e., the expected and actual values are the same at the same index).
# - Count how many *test cases failed* (i.e., the values differ at that index).
# Write a function that returns an object (or dictionary) with the number of *passed* and *failed* test cases.

def test_cases(expected, actual):

  passed = 0
  failed = 0

  for exp, act in zip(expected, actual):
    if exp == act:
      passed += 1
    else:
      failed += 1
  return {'passed': passed, 'failed': failed}

expected = [1, 2, 3, 4, 5]
actual = [1, 2, 3, 0, 5]
result = test_cases(expected, actual)
print(result)
